// Bundles the funnel HTML pages (funnel/*) into a generated TS module so the
// worker can serve them without a filesystem or static-asset fallback.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const funnelDir = join(root, "funnel");

const files = readdirSync(funnelDir).filter((f) => /\.(html|php)$/.test(f));

const entries = files
  .map((f) => `  ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(join(funnelDir, f), "utf8"))},`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/sync-public.mjs. Do not edit.
export const FUNNEL_FILES: Record<string, string> = {
${entries}
};
`;

writeFileSync(join(root, "src/lib/funnel-pages.generated.ts"), out);
console.log(`funnel pages bundled: ${files.join(", ")}`);
